//! Centralized ingress/egress size caps (EP-003, US-013).
//!
//! Every bound that protects an allocation, a parse, or a spawn from untrusted
//! or hand-edited input is gathered here so a read cap and its matching write
//! cap stay in sync - the "validate on both directions" invariant can't
//! silently rot when the two numbers live a screen apart in different files.
//!
//! Four caps are owned by the module/crate that defines their domain and are
//! cross-referenced (not duplicated) here, since moving a `pub(crate)` const
//! would only churn its many import sites for no behavioral gain:
//!
//! - **`MAX_PANES`** (32) - [`crate::layout::MAX_PANES`]. Live UI create cap
//!   (split / drop-to-split / IPC `surface.split` / `workspace.create`) ↔ read
//!   cap in [`paneflow_config::schema::validate_layout`] (US-011) and at session
//!   restore (US-009). With the tab hierarchy it bounds a *tab*, not a
//!   workspace: every create site counts the targeted tab's leaves, and a
//!   workspace's total pane count is the sum over its tabs. This is a **leaf**
//!   cap, not a PTY cap (issue #30).
//! - **`MAX_TABS_PER_WORKSPACE`** (32) - [`crate::workspace::MAX_TABS_PER_WORKSPACE`].
//!   Live tab create cap ↔ `restore_workspaces` truncates a session's tab list,
//!   and [`paneflow_config::schema::MAX_SESSION_TABS`] applies the same bound to
//!   the v1 -> v2 migration (US-018); surplus is logged, not silent.
//! - **`MAX_WORKSPACES`** (20) - [`crate::workspace::MAX_WORKSPACES`]. Live
//!   `workspace.create` cap ↔ `restore_workspaces` cap (US-009).
//! - **`MAX_CONFIG_SIZE_BYTES`** (1 MiB) - `paneflow_config::loader`. Read cap
//!   on `paneflow.json`; the app's own config writer never approaches it.

/// Per-line read cap on untrusted agent-written session JSONL
/// (`claude_sessions`, `codex_sessions`). The agents are the (external) write
/// side; a line over this is treated as malformed and the file is skipped.
/// Deduplicated from two identical `const`s (US-013).
pub(crate) const MAX_LINE_BYTES: u64 = 64 * 1024;

/// Scrollback character cap applied by the WRITE side
/// (`TerminalState::extract_scrollback_from` → `cap_scrollback_at_char_boundary`,
/// US-001) when persisting a pane. Its READ-side counterpart is
/// [`MAX_SESSION_SIZE_BYTES`], which is sized from this × panes × workspaces.
pub(crate) const MAX_CHARS: usize = 400_000;

/// Maximum history rows session persistence and IPC `surface.read` /
/// `surface.search` will walk. `wait`/`flow` request 500 lines and must not
/// materialize this many rows on every GPUI tick (issue #29).
pub(crate) const MAX_SCROLLBACK_EXTRACT_LINES: usize = 4000;

/// Cap on an OSC52 clipboard payload, applied on BOTH the Store (write) and
/// Load (read) paths in the terminal. Deduplicated from two identical `const`s
/// (US-013); keeping one source is what guarantees Store and Load stay
/// symmetric (EP-004 US-015).
pub(crate) const MAX_OSC52_BYTES: usize = 100 * 1024;

/// JSON-RPC framing ceiling on the local IPC socket: the server's per-line read
/// (`read_capped_line` in `ipc.rs`) and the MCP bridge client's reply read
/// (`paneflow_mcp::ipc_client::MAX_RESPONSE_LEN`, a cross-crate mirror of this
/// value) both bound a single request/reply to this many bytes.
pub(crate) const MAX_REQUEST_LEN: u64 = 256 * 1024;

/// Maximum body text returned by `surface.read` before JSON envelope overhead
/// and optional untrusted-output fencing. Kept below [`MAX_REQUEST_LEN`] so a
/// legitimate read response cannot exceed the client-side 256 KiB frame cap.
pub(crate) const MAX_IPC_TEXT_BYTES: usize = 240 * 1024;

/// Read cap on `session.json` (U-008/U-016). Sized from the write side:
/// [`MAX_CHARS`] per pane × `MAX_PANES` × `MAX_WORKSPACES` is a few hundred MB
/// worst-case, but a realistic maxed session is a few MB - 64 MiB sits far
/// above any legitimate session while bounding a multi-hundred-MB tampered file
/// before it is read whole into RAM. Mirrors `MAX_CONFIG_SIZE_BYTES` for
/// `paneflow.json`, which previously had no session-side counterpart.
pub(crate) const MAX_SESSION_SIZE_BYTES: u64 = 64 * 1024 * 1024;

/// Read cap on the markdown scroll-position cache. This file is generated by
/// Paneflow but lives in a user-writable cache directory, so a corrupt or
/// maliciously oversized local file must not be read whole before JSON parse.
pub(crate) const MAX_MARKDOWN_STATE_SIZE_BYTES: u64 = 1024 * 1024;

/// Workspace-level restore cap on PTY-spawning surfaces. Sized from the live
/// write envelope: MAX_TABS_PER_WORKSPACE tabs × MAX_PANES leaves per tab
/// (issue #30). The read-side count is surfaces per layout (a restored pane
/// spawns one PTY), so the ceiling is conservative: a hostile multi-surface
/// leaf still consumes budget before the v2 demotion / mono-surface spawn.
pub(crate) const MAX_WORKSPACE_TERMINALS: usize =
    crate::workspace::MAX_TABS_PER_WORKSPACE * crate::layout::MAX_PANES;

/// Display cap on an untrusted surface label before it is echoed back into app
/// chrome. A terminal's own program controls its OSC title, so every sink that
/// quotes one at the user clamps it here and strips bidi/zero-width controls
/// with `crate::markdown::strip_bidi_zero_width` in the same breath: the
/// port-conflict tooltip (`app/event_handlers.rs`), the fleet-search target
/// list (`app/fleet_search.rs`), and the issue #83 close confirmation
/// (`app/close_confirm.rs`). One constant because the three are the same
/// scrub - they previously read 64, 64 and 48.
pub(crate) const MAX_UNTRUSTED_LABEL_CHARS: usize = 64;

/// Clamp then scrub one untrusted label, in that ORDER.
///
/// The order is load-bearing and was triplicated across the three sinks named
/// above. Clamping first bounds the work the scrub does; scrubbing first would
/// let a title padded with [`MAX_UNTRUSTED_LABEL_CHARS`] zero-width characters
/// keep its visible tail, and clamping a scrubbed string would mean the cap no
/// longer describes anything the caller can reason about. A title that IS
/// nothing but padding renders empty, which is the intended outcome: it had no
/// visible content to show.
pub(crate) fn clamp_untrusted_label(raw: &str) -> String {
    crate::markdown::strip_bidi_zero_width(raw.chars().take(MAX_UNTRUSTED_LABEL_CHARS).collect())
}
