//! Centralized ingress/egress size caps (EP-003, US-013).
//!
//! Every bound that protects an allocation, a parse, or a spawn from untrusted
//! or hand-edited input is gathered here so a read cap and its matching write
//! cap stay in sync - the "validate on both directions" invariant can't
//! silently rot when the two numbers live a screen apart in different files.
//!
//! Four caps are owned by the module/crate that defines their domain and are
//! cross-referenced (not duplicated) here, since moving a `pub(crate)` const
//! would only churn its many import sites for no behavioral gain:
//!
//! - **`MAX_PANES`** (32) - [`crate::layout::MAX_PANES`]. Live UI create cap
//!   (split / drop-to-split / IPC `surface.split` / `workspace.create`) ↔ read
//!   cap in [`paneflow_config::loader::validate_layout`] (US-011) and at session
//!   restore (US-009). This is a **leaf** cap, not a PTY cap (issue #30).
//! - **`MAX_PANE_SURFACES`** (64) - `paneflow_config::loader::MAX_PANE_SURFACES`.
//!   Live `Pane::add_tab` / `add_markdown_tab` write cap ↔ per-pane truncate
//!   in `validate_layout` and session restore (issue #30). The config crate
//!   owns the value because it is a leaf crate; this module re-exports it.
//! - **`MAX_WORKSPACES`** (20) - [`crate::workspace::MAX_WORKSPACES`]. Live
//!   `workspace.create` cap ↔ `restore_workspaces` cap (US-009).
//! - **`MAX_CONFIG_SIZE_BYTES`** (1 MiB) - `paneflow_config::loader`. Read cap
//!   on `paneflow.json`; the app's own config writer never approaches it.

/// Per-line read cap on untrusted agent-written session JSONL
/// (`claude_sessions`, `codex_sessions`). The agents are the (external) write
/// side; a line over this is treated as malformed and the file is skipped.
/// Deduplicated from two identical `const`s (US-013).
pub(crate) const MAX_LINE_BYTES: u64 = 64 * 1024;

/// Scrollback character cap applied by the WRITE side
/// (`TerminalState::extract_scrollback_from` → `cap_scrollback_at_char_boundary`,
/// US-001) when persisting a pane. Its READ-side counterpart is
/// [`MAX_SESSION_SIZE_BYTES`], which is sized from this × panes × workspaces.
pub(crate) const MAX_CHARS: usize = 400_000;

/// Maximum history rows session persistence and IPC `surface.read` /
/// `surface.search` will walk. `wait`/`flow` request 500 lines and must not
/// materialize this many rows on every GPUI tick (issue #29).
pub(crate) const MAX_SCROLLBACK_EXTRACT_LINES: usize = 4000;

/// Cap on an OSC52 clipboard payload, applied on BOTH the Store (write) and
/// Load (read) paths in the terminal. Deduplicated from two identical `const`s
/// (US-013); keeping one source is what guarantees Store and Load stay
/// symmetric (EP-004 US-015).
pub(crate) const MAX_OSC52_BYTES: usize = 100 * 1024;

/// JSON-RPC framing ceiling on the local IPC socket: the server's per-line read
/// (`read_capped_line` in `ipc.rs`) and the MCP bridge client's reply read
/// (`paneflow_mcp::ipc_client::MAX_RESPONSE_LEN`, a cross-crate mirror of this
/// value) both bound a single request/reply to this many bytes.
pub(crate) const MAX_REQUEST_LEN: u64 = 256 * 1024;

/// Maximum body text returned by `surface.read` before JSON envelope overhead
/// and optional untrusted-output fencing. Kept below [`MAX_REQUEST_LEN`] so a
/// legitimate read response cannot exceed the client-side 256 KiB frame cap.
pub(crate) const MAX_IPC_TEXT_BYTES: usize = 240 * 1024;

/// Read cap on `session.json` (U-008/U-016). Sized from the write side:
/// [`MAX_CHARS`] per pane × `MAX_PANES` × `MAX_WORKSPACES` is a few hundred MB
/// worst-case, but a realistic maxed session is a few MB - 64 MiB sits far
/// above any legitimate session while bounding a multi-hundred-MB tampered file
/// before it is read whole into RAM. Mirrors `MAX_CONFIG_SIZE_BYTES` for
/// `paneflow.json`, which previously had no session-side counterpart.
pub(crate) const MAX_SESSION_SIZE_BYTES: u64 = 64 * 1024 * 1024;

/// Read cap on the markdown scroll-position cache. This file is generated by
/// Paneflow but lives in a user-writable cache directory, so a corrupt or
/// maliciously oversized local file must not be read whole before JSON parse.
pub(crate) const MAX_MARKDOWN_STATE_SIZE_BYTES: u64 = 1024 * 1024;

/// Per-pane tab/surface cap (issue #30). Re-export of
/// [`paneflow_config::loader::MAX_PANE_SURFACES`] so live `add_tab` and
/// session restore cannot drift from `validate_layout`'s logged truncate.
/// Includes markdown: the restore cap is surfaces, not terminals-only.
pub(crate) const MAX_PANE_SURFACES: usize = paneflow_config::loader::MAX_PANE_SURFACES;

/// Workspace-level restore cap on PTY-spawning (non-markdown) surfaces.
/// Matches the live write envelope: [`crate::layout::MAX_PANES`] leaves ×
/// [`MAX_PANE_SURFACES`] tabs. `validated_layout_within_cap` counts
/// terminals, not layout leaves, so a single leaf with 64 terminals is
/// accepted while a hostile tree that would spawn more PTYs than this is
/// discarded rather than restored.
pub(crate) const MAX_WORKSPACE_TERMINALS: usize = crate::layout::MAX_PANES * MAX_PANE_SURFACES;
